AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MasterUsername:
    Type: String
    Description: The master username for the database.
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  MasterPassword:
    Type: String
    Description: The master user password for the database.
    MinLength: 8
    MaxLength: 41
    NoEcho: true
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DatabaseName:
    Type: String
    Description: The name of the database to create.
  QoveryJobId:
    Type: String
    Description: The Qovery Job ID to be used in the DBInstanceIdentifier
  VPCSecurityGroupId:
    Type: String
    Description: The VPC security group to associate with the RDS instance

Resources:
  MyDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Sub "db-${QoveryJobId}"
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '16.3'
      MasterUsername: !Sub "${MasterUsername}"
      MasterUserPassword: !Sub "${MasterPassword}"
      DBName: !Sub "${DatabaseName}"
      #iDBSnapshotIdentifier: my-snapshot-identifier
      VPCSecurityGroups:
        - !Sub "${VPCSecurityGroupId}"
      MultiAZ: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      StorageType: gp3
      #StorageEncrypted: true
      #KmsKeyId: put-your-kms-arn-key-here
      Tags:
        - Key: ttl
          Value: 0

Outputs:
  DbInstanceEndpointAddress:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt MyDBInstance.Endpoint.Address
  DbInstanceEndpointPort:
    Description: The port number on which the DB instance is listening
    Value: !GetAtt MyDBInstance.Endpoint.Port
  DbInstanceIdentifier:
    Description: The DB instance identifier
    Value: !GetAtt MyDBInstance.DBInstanceIdentifier
  DbMasterUsername:
    Description: The master username for the database
    Value: !Ref MasterUsername
  DbMasterPassword:
    Description: The master user password for the database
    Value: !Ref MasterPassword
  DatabaseName:
    Description: The name of the database
    Value: !Ref DatabaseName
  VpcSecurityGroupId:
    Description: The VPC security group ID
    Value: !Ref VPCSecurityGroupId
  DatabaseUrl:
    Description: The URL of the database
    Value: !Sub "postgresql://${MasterUsername}:${MasterPassword}@${MyDBInstance.Endpoint.Address}:${MyDBInstance.Endpoint.Port}/${DatabaseName}"
